name: Node CI

on: [push]

jobs:
 
  test-e2e:
    
    runs-on: [ubuntu-16.04]

    strategy:
      matrix:
        cypress-version: ["current", 3.8.3, 3.4.1]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install
      run: |
        yarn install --frozen-lockfile
        [[ ${{ matrix.cypress-version }} == 'current' ]] || yarn add -D cypress@${{ matrix.cypress-version }}
        yarn test-e2e
      env:
        CI: true
