name: Node CI

on: [push]

jobs:
 
  test-e2e:
    
    runs-on: ubuntu-16.04 
    container: cypress/browsers:node12.16.1-chrome80-ff73

    strategy:
      matrix:
        cypress-version: ["current", "current-firefox", 3.8.3, 3.4.1]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install
      run: |
        yarn install --frozen-lockfile
        if [[ ! ${{ matrix.cypress-version }} =~ 'current' ]]; then; yarn add -D cypress@${{ matrix.cypress-version }};fi
        yarn test-e2e $([[ ${{ matrix.cypress-version }} =~ 'firefox' ]] && echo '--browser firefox')
      env:
        CI: true
